site_name: ShyScoreboard
repo_url: https://github.com/Shynixn/ShyScoreboard
site_author: Shynixn
nav:
  - 'ShyScoreboard Wiki':
      - Introduction: README.md
      - Permission: permission.md
      - How to create a scoreboard: installation.md
      - Commands: commands.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.tabs.link
    - content.code.copy
    - navigation.footer
extra:
  generator: false
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
